# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # HiveObject cache classes use EquatableMixin for value equality while
    # HiveObjectMixin has mutable _box/_key fields for Hive's storage tracking.
    # JMAP method classes use Optional* mixins with mutable fields by design.
    # These are intentional architectural patterns, not bugs.
    must_be_immutable: ignore

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    unnecessary_string_escapes: false
