// Mocks generated by Mockito 5.0.17 from annotations
// in tmail_ui_user/test/features/mailbox/domain/usecases/get_all_mailbox_interactor_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:jmap_dart_client/jmap/account_id.dart' as _i5;
import 'package:jmap_dart_client/jmap/core/properties/properties.dart' as _i6;
import 'package:jmap_dart_client/jmap/core/state.dart' as _i7;
import 'package:jmap_dart_client/jmap/mail/mailbox/mailbox.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tmail_ui_user/features/mailbox/domain/model/create_new_mailbox_request.dart'
    as _i9;
import 'package:tmail_ui_user/features/mailbox/domain/model/mailbox_response.dart'
    as _i4;
import 'package:tmail_ui_user/features/mailbox/domain/model/rename_mailbox_request.dart'
    as _i10;
import 'package:tmail_ui_user/features/mailbox/domain/repository/mailbox_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MailboxRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMailboxRepository extends _i1.Mock implements _i2.MailboxRepository {
  MockMailboxRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.MailboxResponse> getAllMailbox(_i5.AccountId? accountId,
          {_i6.Properties? properties}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAllMailbox, [accountId], {#properties: properties}),
              returnValue: Stream<_i4.MailboxResponse>.empty())
          as _i3.Stream<_i4.MailboxResponse>);
  @override
  _i3.Stream<_i4.MailboxResponse> refresh(
          _i5.AccountId? accountId, _i7.State? currentState) =>
      (super.noSuchMethod(
              Invocation.method(#refresh, [accountId, currentState]),
              returnValue: Stream<_i4.MailboxResponse>.empty())
          as _i3.Stream<_i4.MailboxResponse>);
  @override
  _i3.Future<_i8.Mailbox?> createNewMailbox(_i5.AccountId? accountId,
          _i9.CreateNewMailboxRequest? newMailboxRequest) =>
      (super.noSuchMethod(
          Invocation.method(#createNewMailbox, [accountId, newMailboxRequest]),
          returnValue:
              Future<_i8.Mailbox?>.value()) as _i3.Future<_i8.Mailbox?>);
  @override
  _i3.Future<bool> deleteMultipleMailbox(
          _i5.AccountId? accountId, List<_i8.MailboxId>? mailboxIds) =>
      (super.noSuchMethod(
          Invocation.method(#deleteMultipleMailbox, [accountId, mailboxIds]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> renameMailbox(
          _i5.AccountId? accountId, _i10.RenameMailboxRequest? request) =>
      (super.noSuchMethod(
          Invocation.method(#renameMailbox, [accountId, request]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
