// Mocks generated by Mockito 5.0.10 from annotations
// in tmail_ui_user/test/features/mailbox/domain/usecases/refresh_all_mailbox_interactor_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:jmap_dart_client/jmap/account_id.dart' as _i5;
import 'package:jmap_dart_client/jmap/core/properties/properties.dart' as _i6;
import 'package:jmap_dart_client/jmap/core/state.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tmail_ui_user/features/mailbox/data/model/mailbox_response.dart'
    as _i4;
import 'package:tmail_ui_user/features/mailbox/domain/repository/mailbox_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MailboxRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMailboxRepository extends _i1.Mock implements _i2.MailboxRepository {
  MockMailboxRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.MailboxResponse> getAllMailbox(_i5.AccountId? accountId,
          {_i6.Properties? properties}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAllMailbox, [accountId], {#properties: properties}),
              returnValue: Stream<_i4.MailboxResponse>.empty())
          as _i3.Stream<_i4.MailboxResponse>);
  @override
  _i3.Stream<_i4.MailboxResponse> refresh(
          _i5.AccountId? accountId, _i7.State? currentState) =>
      (super.noSuchMethod(
              Invocation.method(#refresh, [accountId, currentState]),
              returnValue: Stream<_i4.MailboxResponse>.empty())
          as _i3.Stream<_i4.MailboxResponse>);
}
