version: "3"

services:
  tmail-backend:
    image: linagora/tmail-backend:memory-1.0.0
    container_name: tmail-backend
    volumes:
      - ./jwt_publickey:/root/conf/jwt_publickey
      - ./jwt_privatekey:/root/conf/jwt_privatekey
      - ./mailetcontainer.xml:/root/conf/mailetcontainer.xml
      - ./imapserver.xml:/root/conf/imapserver.xml
      - ./jmap.properties:/root/conf/jmap.properties
      - ../provisioning/integration_test/search_email_with_sort_order/provisioning.sh:/root/conf/integration_test/search_email_with_sort_order/provisioning.sh
      - ../provisioning/integration_test/search_email_with_sort_order/eml:/root/conf/integration_test/search_email_with_sort_order/eml
    ports:
      - "80:80"
    environment:
      - DOMAIN=example.com
    networks:
      - tmail

networks:
  tmail:
