
enum EmailActionType {
  reply,
  forward,
  replyAll,
  compose,
  markAsRead,
  markAsUnread,
  markAsStarred,
  unMarkAsStarred,
  moveToMailbox,
  editDraft,
  editSendingEmail,
  composeFromContentShared,
  composeFromFileShared,
  composeFromEmailAddress,
  composeFromMailtoURL,
  reopenComposerBrowser,
  moveToTrash,
  deletePermanently,
  preview,
  selection,
  moveToSpam,
  unSpam,
  openInNewTab
}