on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

name: Build dev binaries

env:
  FLUTTER_VERSION: 3.38.9
  XCODE_VERSION: 26.2


permissions:
  contents: read
jobs:
  build-app:
    name: Build app
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: android
            runner: ubuntu-latest
          - os: ios
            runner: macos-15 # Use macos-15 runners because Xcode 26 requires macOS 15+.
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Setup Fastlane
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ${{ matrix.os }}

      - name: Setup Firebase env
        env:
          FIREBASE_ENV: ${{ secrets.FIREBASE_ENV }}
        run: ./scripts/setup-firebase.sh

      - name: Setup Java
        if: matrix.os == 'android'
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Select Xcode version
        if: matrix.os == 'ios'
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup iOS environment
        if: matrix.os == 'ios'
        run: ../scripts/setup-ios.sh
        working-directory: ${{ matrix.os }}

      - name: Run prebuild
        run: ./scripts/prebuild.sh

      - name: Build
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPLE_CERTIFICATES_SSH_KEY: ${{ secrets.APPLE_CERTIFICATES_SSH_KEY }}
        run: ../scripts/build-dev.sh
        working-directory: ${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: tmail-dev-${{ matrix.os }}
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            ios/Runner.ipa
