name: Web integration tests

on:
  pull_request:
    paths-ignore:
      - ".github/**"
      - "docs"
      - "Jenkinsfile"
      - "**/*.md"

env:
  FLUTTER_VERSION: 3.38.9

jobs:
  web_integration_test:
    permissions:
      contents: "read"
      id-token: "write"

    name: Run integration tests for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Run prebuild
        run: ./scripts/prebuild.sh

      - name: Test
        run: ./scripts/patrol-web-integration-test-with-docker.sh
