on:
  pull_request:
    # paths:
    #   - "**/*.dart"

name: Deploy PR on Cloudflare Pages

jobs:
  deploy:
    name: Build TMail web version and deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.alias }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.5"
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('**/pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Run prebuild
        run: bash prebuild.sh

      - name: Build TMail web
        run: flutter build web --profile

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "tmail-web"
          directory: "build/web"

      - name: Find deployment comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          comment-author: "github-actions[bot]"
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "This PR"

      - name: Create or update deployment comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This PR has been deployed to ${{ steps.deploy.outputs.alias }}
          edit-mode: replace
